# Generated by Django 4.2.27 on 2025-12-25 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucPhanThuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phan_thuong', models.CharField(max_length=150, unique=True, verbose_name='Tên phần thưởng')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('gia_tri', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá trị (VNĐ)')),
            ],
            options={
                'verbose_name_plural': 'Danh Mục Phần Thưởng',
            },
        ),
        migrations.CreateModel(
            name='HoGiaDinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ho', models.CharField(max_length=10, unique=True, verbose_name='Mã Hộ')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa Chỉ')),
            ],
            options={
                'verbose_name_plural': 'Hộ Gia Đình',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TO_TRUONG', 'Tổ trưởng'), ('TO_PHO', 'Tổ phó'), ('CAN_BO_NHAN_KHAU', 'Cán bộ nhân khẩu'), ('CAN_BO_HANH_CHINH', 'Cán bộ hành chính'), ('NGUOI_DAN', 'Người dân')], default='NGUOI_DAN', max_length=30, verbose_name='Vai trò')),
                ('ho_gia_dinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hogiadinh', verbose_name='Thuộc hộ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ Tên')),
                ('cccd', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='CCCD')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày Sinh')),
                ('gioi_tinh', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nu', 'Nữ'), ('Khac', 'Khác')], max_length=10, null=True, verbose_name='Giới tính')),
                ('quan_he_chu_ho', models.CharField(blank=True, max_length=50, verbose_name='Quan hệ với chủ hộ')),
                ('la_chu_ho', models.BooleanField(default=False, verbose_name='Là chủ hộ')),
                ('trang_thai', models.CharField(choices=[('ThuongTru', 'Thường trú'), ('TamTru', 'Tạm trú'), ('ChuyenDi', 'Chuyển đi')], default='ThuongTru', max_length=20, verbose_name='Trạng thái cư trú')),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_vien_trong_ho', to='core.hogiadinh', verbose_name='Hộ Gia Đình')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thanh_vien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Thành Viên',
            },
        ),
        migrations.CreateModel(
            name='TamVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_den', models.CharField(max_length=255, verbose_name='Nơi chuyển đến')),
                ('ly_do', models.TextField(verbose_name='Lý do')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày đi')),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True, verbose_name='Ngày về dự kiến')),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DaDuyet', 'Đã duyệt'), ('TuChoi', 'Từ chối')], default='ChoDuyet', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu_can_bo', models.TextField(blank=True, verbose_name='Ý kiến cán bộ')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_tam_vang', to='core.thanhvien', verbose_name='Người đăng ký')),
            ],
            options={
                'verbose_name_plural': 'Đơn Tạm Vắng',
            },
        ),
        migrations.CreateModel(
            name='TamTru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_chi_thuong_tru_goc', models.CharField(max_length=255, verbose_name='Đ/C Thường trú gốc')),
                ('dia_chi_tam_tru', models.CharField(max_length=255, verbose_name='Đ/C Tạm trú tại đây')),
                ('ly_do', models.TextField(verbose_name='Lý do')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DaDuyet', 'Đã duyệt'), ('TuChoi', 'Từ chối')], default='ChoDuyet', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu_can_bo', models.TextField(blank=True, verbose_name='Ý kiến cán bộ')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_tam_tru', to='core.thanhvien', verbose_name='Người đăng ký')),
            ],
            options={
                'verbose_name_plural': 'Đơn Tạm Trú',
            },
        ),
        migrations.CreateModel(
            name='LichSuPhatThuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_phat', models.CharField(max_length=100, verbose_name='Đợt phát (VD: Trung Thu 2025)')),
                ('minh_chung', models.ImageField(blank=True, null=True, upload_to='minh_chung/', verbose_name='Ảnh minh chứng (Giấy khen)')),
                ('trang_thai', models.CharField(choices=[('ChuaNhan', 'Chưa nhận'), ('DaNhan', 'Đã nhận')], default='ChuaNhan', max_length=20, verbose_name='Trạng thái')),
                ('ngay_cap_phat', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('nguoi_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ thực hiện')),
                ('phan_thuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.danhmucphanthuong', verbose_name='Phần thưởng')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_nhan_thuong', to='core.thanhvien', verbose_name='Người nhận')),
            ],
            options={
                'verbose_name_plural': 'Lịch Sử Phát Thưởng',
            },
        ),
        migrations.AddField(
            model_name='hogiadinh',
            name='chu_ho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ho_lam_chu', to='core.thanhvien', verbose_name='Chủ Hộ'),
        ),
    ]
