# Generated by Django 4.2.27 on 2025-12-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamtru',
            options={'ordering': ['-ngay_tao'], 'verbose_name_plural': 'Đơn Tạm Trú'},
        ),
        migrations.AlterModelOptions(
            name='tamvang',
            options={'ordering': ['-ngay_tao'], 'verbose_name_plural': 'Đơn Tạm Vắng'},
        ),
        migrations.RemoveField(
            model_name='tamtru',
            name='dia_chi_tam_tru',
        ),
        migrations.RemoveField(
            model_name='tamtru',
            name='dia_chi_thuong_tru_goc',
        ),
        migrations.RemoveField(
            model_name='tamtru',
            name='ly_do',
        ),
        migrations.AddField(
            model_name='tamtru',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, verbose_name='Số CCCD'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='chu_ho_cccd',
            field=models.CharField(blank=True, max_length=12, verbose_name='Số CCCD chủ hộ'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='chu_ho_ten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ tên chủ hộ'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='chu_so_huu_cccd',
            field=models.CharField(blank=True, max_length=12, verbose_name='Số CCCD chủ sở hữu'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='chu_so_huu_nam_sinh',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm sinh chủ sở hữu'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='chu_so_huu_ten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ tên chủ sở hữu'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='dia_chi_thuong_tru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ thường trú'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='gioi_tinh',
            field=models.CharField(blank=True, max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ tên người đăng ký'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='moi_quan_he',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mối quan hệ với chủ hộ'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='ngay_duyet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='ngay_tao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo đơn'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='noi_tam_tru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nơi đề nghị tạm trú'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='tamtru',
            name='thoi_han_tam_tru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Thời hạn tạm trú'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, verbose_name='Số CCCD'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='dia_chi_thuong_tru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ thường trú'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='gioi_tinh',
            field=models.CharField(blank=True, max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ tên người đăng ký'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='ngay_duyet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='ngay_tao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo đơn'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='tamvang',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='tamtru',
            name='ngay_bat_dau',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu tạm trú'),
        ),
        migrations.AlterField(
            model_name='tamtru',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc tạm trú'),
        ),
        migrations.AlterField(
            model_name='tamtru',
            name='thanh_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_tam_tru', to='core.thanhvien', verbose_name='Người đăng ký (nếu có trong hệ thống)'),
        ),
        migrations.AlterField(
            model_name='tamvang',
            name='ly_do',
            field=models.TextField(blank=True, verbose_name='Lý do tạm vắng'),
        ),
        migrations.AlterField(
            model_name='tamvang',
            name='ngay_bat_dau',
            field=models.DateField(blank=True, null=True, verbose_name='Tạm vắng từ ngày'),
        ),
        migrations.AlterField(
            model_name='tamvang',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, null=True, verbose_name='Đến ngày'),
        ),
        migrations.AlterField(
            model_name='tamvang',
            name='noi_den',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ nơi đến'),
        ),
        migrations.AlterField(
            model_name='tamvang',
            name='thanh_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_tam_vang', to='core.thanhvien', verbose_name='Người đăng ký (nếu có trong hệ thống)'),
        ),
    ]
