# Generated by Django 4.2.27 on 2025-12-30 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_tamtru_options_alter_tamvang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanhvien',
            name='bi_danh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bí danh'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='dan_toc',
            field=models.CharField(blank=True, default='Kinh', max_length=50, verbose_name='Dân tộc'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='dia_chi_truoc_chuyen_den',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ trước khi chuyển đến'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='ghi_chu_thay_doi',
            field=models.TextField(blank=True, verbose_name='Ghi chú thay đổi'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='ngay_cap_cccd',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cấp CCCD'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='ngay_chuyen_di',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày chuyển đi'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='ngay_dang_ky_thuong_tru',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đăng ký thường trú'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='nghe_nghiep',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nghề nghiệp'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='nguyen_quan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nguyên quán'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='noi_cap_cccd',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nơi cấp CCCD'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='noi_chuyen_den',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nơi chuyển đến'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='noi_lam_viec',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nơi làm việc'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='noi_sinh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nơi sinh'),
        ),
        migrations.CreateModel(
            name='LichSuThayDoiHo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_thay_doi', models.CharField(choices=[('DoiChuHo', 'Đổi chủ hộ'), ('DoiDiaChi', 'Đổi địa chỉ'), ('TachHo', 'Tách hộ'), ('Khac', 'Khác')], max_length=20, verbose_name='Loại thay đổi')),
                ('noi_dung', models.TextField(verbose_name='Nội dung thay đổi')),
                ('ngay_thay_doi', models.DateField(verbose_name='Ngày thay đổi')),
                ('ngay_ghi_nhan', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ghi nhận vào hệ thống')),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thay_doi', to='core.hogiadinh', verbose_name='Hộ gia đình')),
                ('nguoi_thuc_hien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện (admin)')),
            ],
            options={
                'verbose_name_plural': 'Lịch Sử Thay Đổi Hộ',
                'ordering': ['-ngay_thay_doi'],
            },
        ),
    ]
