# Generated by Django 4.2.27 on 2025-12-31 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_thanhvien_bi_danh_thanhvien_dan_toc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsuphatthuong',
            name='loai_phat_thuong',
            field=models.CharField(choices=[('DipLe', 'Dịp lễ (Trung thu, Tết thiếu nhi...)'), ('HocTap', 'Thành tích học tập'), ('Khac', 'Khác')], default='DipLe', max_length=20, verbose_name='Loại phát thưởng'),
        ),
        migrations.AddField(
            model_name='lichsuphatthuong',
            name='so_luong',
            field=models.IntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.CreateModel(
            name='ThongTinHocTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(max_length=20, verbose_name='Năm học (VD: 2024-2025)')),
                ('truong', models.CharField(max_length=200, verbose_name='Trường')),
                ('lop', models.CharField(max_length=50, verbose_name='Lớp')),
                ('thanh_tich', models.CharField(choices=[('HocSinhGioi', 'Học sinh giỏi'), ('ThanhTichDacBiet', 'Thành tích đặc biệt'), ('HocSinhTienTien', 'Học sinh tiên tiến'), ('Khac', 'Khác')], max_length=30, verbose_name='Thành tích')),
                ('minh_chung', models.ImageField(blank=True, null=True, upload_to='minh_chung_hoc_tap/', verbose_name='Ảnh giấy khen/bằng khen')),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DaDuyet', 'Đã duyệt'), ('TuChoi', 'Từ chối')], default='ChoDuyet', max_length=20, verbose_name='Trạng thái')),
                ('ngay_duyet', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('ly_do_tu_choi', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duyet_hoc_tap', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tao_thong_tin_hoc_tap', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_tin_hoc_tap', to='core.thanhvien', verbose_name='Học sinh')),
            ],
            options={
                'verbose_name_plural': 'Thông Tin Học Tập',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.AddField(
            model_name='lichsuphatthuong',
            name='thong_tin_hoc_tap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phan_thuong_nhan', to='core.thongtinhoctap', verbose_name='Thông tin học tập'),
        ),
    ]
