# Generated by Django 4.2.27 on 2025-12-31 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_lichsuphatthuong_loai_phat_thuong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotPhatThuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dot', models.CharField(max_length=200, verbose_name='Tên đợt phát thưởng')),
                ('nam_hoc', models.CharField(max_length=20, verbose_name='Năm học (VD: 2024-2025)')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu nhận hồ sơ')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Ngày kết thúc nhận hồ sơ')),
                ('trang_thai', models.CharField(choices=[('DangMo', 'Đang mở - Nhận hồ sơ'), ('DaDong', 'Đã đóng - Không nhận thêm'), ('DangPhat', 'Đang phát thưởng'), ('HoanThanh', 'Hoàn thành')], default='DangMo', max_length=20, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tao_dot_phat_thuong', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name_plural': 'Đợt Phát Thưởng',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.AddField(
            model_name='thongtinhoctap',
            name='dot_phat_thuong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_thanh_tich', to='core.dotphatthuong', verbose_name='Đợt phát thưởng'),
        ),
    ]
