# Generated by Django 4.2.27 on 2025-12-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dotphatthuong_thongtinhoctap_dot_phat_thuong'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotphatthuong',
            name='loai_dot',
            field=models.CharField(choices=[('KhenThuong', 'Khen thưởng học tập'), ('LeTet', 'Lễ Tết')], default='KhenThuong', max_length=20, verbose_name='Loại đợt'),
        ),
        migrations.AddField(
            model_name='dotphatthuong',
            name='tuoi_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tuổi tối đa (cho đợt Lễ Tết)'),
        ),
        migrations.AddField(
            model_name='dotphatthuong',
            name='tuoi_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tuổi tối thiểu (cho đợt Lễ Tết)'),
        ),
    ]
