# Generated by Django 4.2.27 on 2025-12-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dotphatthuong_loai_dot_dotphatthuong_tuoi_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotphatthuong',
            name='nam_hoc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Năm học (VD: 2024-2025)'),
        ),
    ]
