# Generated by Django 4.2.27 on 2025-12-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dotphatthuong_nam_hoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtinhoctap',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=200, verbose_name='Họ tên học sinh'),
        ),
        migrations.AlterField(
            model_name='thongtinhoctap',
            name='nam_hoc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Năm học (VD: 2024-2025)'),
        ),
    ]
