# Generated by Django 4.2.27 on 2025-12-31 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_thongtinhoctap_ho_ten_alter_thongtinhoctap_nam_hoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuThayDoiThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_thay_doi', models.CharField(choices=[('ThemMoi', 'Thêm mới'), ('ChinhSua', 'Chỉnh sửa thông tin'), ('ChuyenDi', 'Chuyển đi'), ('QuaDoi', 'Qua đời'), ('TachHo', 'Tách hộ'), ('Khac', 'Khác')], max_length=20, verbose_name='Loại thay đổi')),
                ('noi_dung', models.TextField(verbose_name='Nội dung thay đổi')),
                ('ngay_thay_doi', models.DateField(verbose_name='Ngày thay đổi')),
                ('noi_chuyen_den', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi chuyển đến')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_ghi_nhan', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ghi nhận vào hệ thống')),
                ('nguoi_thuc_hien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện (admin)')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thay_doi', to='core.thanhvien', verbose_name='Thành viên')),
            ],
            options={
                'verbose_name_plural': 'Lịch Sử Thay Đổi Nhân Khẩu',
                'ordering': ['-ngay_thay_doi'],
            },
        ),
    ]
