# Generated by Django 4.2.27 on 2025-12-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lichsuthaydoithanhvien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanhvien',
            name='noi_chuyen_den',
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='dia_chi_chuyen_di',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ chuyển đi'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='ngay_qua_doi',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày qua đời'),
        ),
        migrations.AlterField(
            model_name='thanhvien',
            name='trang_thai',
            field=models.CharField(choices=[('ThuongTru', 'Thường trú'), ('TamTru', 'Tạm trú'), ('ChuyenDi', 'Chuyển đi'), ('DaQuaDoi', 'Đã qua đời')], default='ThuongTru', max_length=20, verbose_name='Trạng thái cư trú'),
        ),
    ]
