# Generated by Django 4.2.27 on 2025-12-19 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucPhanThuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phan_thuong', models.CharField(max_length=150, unique=True, verbose_name='Tên Phần Thưởng')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô Tả')),
                ('gia_tri', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá Trị (VNĐ)')),
            ],
            options={
                'verbose_name_plural': 'Danh Mục Phần Thưởng',
            },
        ),
        migrations.CreateModel(
            name='HoGiaDinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ho', models.CharField(max_length=10, unique=True, verbose_name='Mã Hộ')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa Chỉ')),
                ('ten_chu_ho', models.CharField(max_length=100, verbose_name='Tên Chủ Hộ')),
            ],
            options={
                'verbose_name_plural': 'Hộ Gia Đình',
            },
        ),
        migrations.CreateModel(
            name='ThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ Tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày Sinh')),
                ('quan_he_chu_ho', models.CharField(max_length=50, verbose_name='Quan Hệ với Chủ Hộ')),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_vien_trong_ho', to='core.hogiadinh')),
            ],
            options={
                'verbose_name_plural': 'Thành Viên',
            },
        ),
        migrations.CreateModel(
            name='LichSuPhatThuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cap_phat', models.DateField(auto_now_add=True, verbose_name='Ngày Cấp Phát')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi Chú')),
                ('nguoi_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phan_thuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.danhmucphanthuong')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_nhan_thuong', to='core.thanhvien')),
            ],
            options={
                'verbose_name_plural': 'Lịch Sử Phát Thưởng',
            },
        ),
    ]
