# Generated by Django 4.2.27 on 2025-12-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanhvien',
            name='la_chu_ho',
            field=models.BooleanField(default=False, verbose_name='Là chủ hộ'),
        ),
        migrations.AlterField(
            model_name='danhmucphanthuong',
            name='mo_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lichsuphatthuong',
            name='ghi_chu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lichsuphatthuong',
            name='ngay_cap_phat',
            field=models.DateField(auto_now_add=True),
        ),
    ]
