# Generated by Django 4.2.27 on 2025-12-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_thanhvien_la_chu_ho_alter_danhmucphanthuong_mo_ta_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='thanhvien',
            constraint=models.UniqueConstraint(condition=models.Q(('la_chu_ho', True)), fields=('ho_gia_dinh',), name='unique_chu_ho_per_ho'),
        ),
    ]
